added funcion latest-release (lr)

diff --git a/bashrc-append b/bashrc-append
--- a/bashrc-append
+++ b/bashrc-append
@@ -29,4 +29,17 @@ else
 fi
 unset color_prompt
 
+function latest-branch {
+    e1=0
+    git checkout master 2> /dev/null 1> /dev/null || ((++e1))
+    git checkout main   2> /dev/null 1> /dev/null || ((++e1))
+    if [[ $eq -gt 1 ]]; then
+        echo "error - could not check into neither master nor main"
+        exit 1
+    fi
+    lr=$(git branch -r | grep -E -- 'release\/2[0-9]{2}\.[0-9]{1,3}\.[0-9]{1,3}$' | tail -n 1 | sed 's/origin\///')
+    git checkout $lr 2> /dev/null 1> /dev/null
+}
+alias lr="\$(latest-branch)"
+
 #juliano-bashrc-config-done
